### ISSUE TITLE
"Don't know how to build task 'oidc_provider:install:migrations'"

### ISSUE THREAD

**Issue by mchavarriagam** [brandnewbox/oidc_provider#4]
Hi,

Apologies in advance for what is probably a silly beginner's question, but could not find any info related to this issue.

I'm trying to follow the documentation for setting up the gem, both here: https://www.rubydoc.info/gems/oidc_provider/0.3.9 and here https://github.com/brandnewbox/oidc_provider

When I run `rails oidc_provider:install:migrations` I get the error described in the title ("Don't know how to build..."). If I run `rails --tasks` there's no entry for oidc_provider.

Am I missing something?

Thanks.

**Comment by nathancolgate** [comment]
@mchavarriagam Apologies for not getting back to you sooner. This is not an actively maintained project on our team.  You're welcome to try moving the migrations by hand. They are located here:

https://github.com/brandnewbox/oidc_provider/tree/fcb4fbfe0e7a3a3b10eed136238775b43032751e/db/migrate

**Comment by mchavarriagam** [comment]
Hi @nathancolgate on the contrary, thanks for taking the time to get back to me on this, and thanks for the info!
